### ISSUE TITLE
Client run issues

### ISSUE THREAD

**Issue by nanocosmos-ol** [aws-samples/aws-iot-chat-example#38]
When trying to start the client it fails:

option 1: run "npm start"
- this opens a web page on http://localhost:3000 showing a error log "TypeError: Cannot read property 'render' of undefined"

option 2: "npm run build" and then "serve -s build"
this opens a page on http://localhost:5000 which shows UI to signup. When I try to register, this error is shown on the page:
PreSignUp failed with error Error: Cannot find module 'babel-runtime/regenerator'.

What is the correct way of running the client?

**Comment by oyenikhil** [comment]
Facing the same issue after I run "npm start"

`social-login.js:1 Uncaught TypeError: Cannot read property 'render' of undefined
    at new n (social-login.js:1)`

**Comment by Nosajool** [comment]
Hi, option 1 is the intended command. When I run it, I can reproduce this error.

Will try to spend some time to investigate the root cause. Guessing that the version update to `react` or `react-dom` caused this. I've been out of the javascript ecosystem for awhile so will need to do some change log reading over the weekend.

**Comment by Nosajool** [comment]
I had unintentionally updated a dependency that broke the client. Latest commit should fix the issue that you are seeing. Please open another issue if you are still seeing errors. 🙂
