### ISSUE TITLE
detache policy script error

### ISSUE THREAD

**Issue by supun19** [aws-samples/aws-iot-chat-example#7]
`Error: Command failed: ./scripts/detach_policies.sh
./scripts/detach_policies.sh: 7: ./scripts/detach_policies.sh: Syntax error: "(" unexpected

**Comment by mdg215199** [comment]
Just now trying this repos, just in case anyone else has this same issue, please be sure to read the issue written in 09 https://github.com/aws-samples/aws-iot-chat-example/issues/9

It's the same issue.  As the original commented specified above, 

"So what's going on here? Within your .aws/credentials or .aws/config options, change the output field to json. Now, jq will be able to correctly parse the JSON results from the aws cli commands. The root cause is that you must have had the output set to text."

If you do this, you will have no issues.
